### PR TITLE
New features and rewrote of working internals

### PR DESCRIPTION
**Pull request by evandrocoan**

### CODE REVIEW

**Comment by nikoargo** [comment]
Wow! I am excited by your passion for WordHighlight. Is there any way you could break this up into multiple PRs so that it's easier to review, or maybe clean up the history so it can be reviewed one clean commit at a time? Thanks!

**Comment by adzenith** [comment]
Wow! I am excited by your passion for WordHighlight. Is there any way you could break this up into multiple PRs so that it's easier to review, or maybe clean up the history so it can be reviewed one clean commit at a time? Thanks!

**Comment by sublimator** [comment]
+1

**Comment by evandrocoan** [comment]
You should read very carefully each word I wrote because they are very subtle and precise. Also, I am not a native English Speaker, then, may be something I wrote cannot be understandable on first sight.

Nothing on this text is directed to your person, or it has anything with what you have done. It is just my accumulated frustration over the years with open source projects pull request requirements. This was just it, the last one required for me to unleash my wrath.

I do not know what do say here. I just went very wild committing stuff and fixing whatever problem I could find and adding whatever feature I would like.

This is working 100% on Windows, but on Linux the `Ctrl+D`/`Alt+D` feature is sometimes (i.e., randomly, and may be related to https://github.com/SublimeTextIssues/Core/issues/2937) double selecting words. I did not have the time yet to track down why Sublime Text is bad behaving on Linux. 

If I would go to spend more time with this plugin, it would be tracking it down and fixing the double selection bug on Linux. Then, for me it is easier to just close this pull request instead of rewriting the git history, either renaming/squashing commits or splitting it with multiple pull requests.

Undoubtedly, if did everything as you asked, i.e., adding pull requests for each feature/bug fix, it would require from me much more work/time. Indeed, working with several pull requests is:
1. The best way to work on a large project where concurrently several people are committing at the same time. But that is not the case here.
1. The easiest way for you to deeply review my code changes. Do you really need to deep review them?

On the last 2 years, I alone committed into my master branch and I was the only one working (while also keeping it up-to-date with this upstream changes). So, the overhead time of splitting everything into countless pull requests can definitely be spent for me writing more code on another open source projects I also work on. (Of course, this is also valid for you too (reviewing it). Unless you quit the idea of deep review my code and accept to merge it just by superficially reviewing it, or just installing it and using it and see if everything still working as expected)

As it is a very deep rewrite, to review it, one would just be required to get the latest version and read the main file upside-down. If this is too much for you, then, either:
1. Do not review it, and merge it anyways because you trust me
1. Review it superficially, and merge because you trusted the code you superficially saw
1. Install it on your computer and just use it. If you find bugs, report them.
1. Close this pull request and pretend I do not exist. If you choose this, for me there is no problem. I just opened this pull request because I liked my changes very much and would like to share them. But, I can also do that by releasing this as a new package on Package Control under a new name.

I would definitely call this (splitting everything into countless pull requests) a case of over engineering and splitting the open source community (now there is your project and my fork project as completely independent code bases). This is very small project and there is no need for such management overhead. As just explained, this work flow (several small pull requests, i.e., [git flow](https://nvie.com/posts/a-successful-git-branching-model/) itself) is good for large and high active projects, unless:
1. Do you think I wrote some backdoor on this code to steal peoples data and you need to deep review it?
1. Do you think I definitely broke backward compatibility and once merging this, it would badly break this plugin for all its users?
1. Do you think I am a very bad programmer and I my work should be very deep inspected because I am introducing all kinds of errors, unknown and wrong behaviors?

If you do not agree with nothing of the above and still requires to split everything into countless pull requests, it is better for me and for you, to just close this pull request and let us both work as independent projects. It would much better than keep fighting over whitespaces and function names.

Please, I do not want to start a fight. Right now, everything I want to is finish writing my graduation thesis, find a good job and keep using Sublime Text with this and much others countless and good plugins there are for it. (And of course, fix that damn double selection bug on Linux too).

I am just pissed off because it is very frequent to find people over engineering small projects like this. It just a waist of time which could be well spend working somewhere else. At least for me, this is a small project. May be for this is a big project, then, all I can do is say sorry for opening this pull request and wasting your time reading this.

May be for you, this is not over engineering because you are right and this not over engineering and I am the one which is actually under engendering it. Probably I just went insane because I put myself into maintaining over [200 packages](https://github.com/evandrocoan/ITE/tree/master/Packages) and this is just more one of them on my maintainment list. Do not take me bad, I did not commit to all of them (yet), but each time a new bug emerges, or a new feature is required, I am there writing it! Yeah, coding until you bleeeeeeed! Is there a bug? It only has a ugly workaround? I am definitely doing! All I want to is to definitely get it working!

**Pull request closed without merging**
